import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { WalletObserver } from '../components/wallet/WalletObserver';

// wagmiProvider
import { Web3Provider } from '../provider/Web3Provider';

// layout
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-900 bg-white`}
      >
        <Web3Provider>
          <WalletObserver />

          <div className="flex flex-col min-h-screen">
            <Navbar />

            <main className="grow w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
              {children}
            </main>

            <Footer />
          </div>

          <Toaster position="top-right" richColors closeButton />
        </Web3Provider>
      </body>
    </html>
  );
}
